version: "3.9"

services:
  backend:
    build: ./backend
    image: toantra349/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    group_add:
      - "999"
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    image: toantra349/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
